language: ruby
rvm:
- 2.1
install:
  - gem install jekyll
  - gem install jekyll-redirect-from
  - gem install html-proofer
script:
  - jekyll build
  - htmlproof _site --href-ignore https://www.drupal.org/ , http://www.opencart.com/ , https://www.drupal.org/drupal-6.0 , https://www.drupal.org/drupal-7.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
