# Site settings

title: Mr PHP
email: contact@mrphp.com.au
address: PO Box 2030, Hackham, SA 5163
phone: (08) 8463 1298
abn: 30551301857

description: >
  Providing contract and freelance web development services since 2000.
  We specialise in building custom cloud based applications using agile development techniques.
about: >
  Mr PHP was founded by Brett O'Donnell in 2000, and has been making web software ever since.

image_src: /assets/img/logo/logo.png
header_img: /assets/img/background/index.jpg
url: http://mrphp.com.au
baseurl: ""

twitter_username: mrphp
github_username:  cornernote
facebook_page: pages/Mr-PHP/124929103375
linkedin_company: mr-php
mailchimp_subscribe_url: http://mrphp.us1.list-manage.com/subscribe?u=91727179f1c05b357b43bb4d3&id=4122328387


# Build settings
permalink: /blog/:title
paginate_path: /blog/page:num
paginate: 10
excerpt_separator: <!--break-->
markdown: redcarpet
highlighter: pygments
exclude: ["README.md"]
gems:
- jekyll-redirect-from