# Site settings

title: Mr PHP
name: MrPHP.com.au
email: hello@mrphp.com.au
address: PO Box 2030, Hackham, SA 5163
phone: (08) 8463 1298
phone_int: +61884631298
abn: 30 551 301 857

description: >
  Specialising in building custom web based applications using agile development techniques.
  PHP developer providing freelance and contract services since 2000.
  Located in Adelaide, also servicing Brisbane, Sydney, Melbourne and Australia.
about: >
  Mr PHP was founded by <a href="https://cornernote.github.io/">Brett O'Donnell</a> in 2000, and has been making web software ever since.

image_src: /assets/img/logo/logo.png
header_img: /assets/img/background/index.jpg
url: https://mrphp.com.au
baseurl: ""

twitter_username: mrphp
github_username:  cornernote
facebook_page: pages/Mr-PHP/124929103375
google_plus_page: 105251425294714122907
linkedin_company: mr-php
mailchimp_subscribe_url: http://mrphp.us1.list-manage.com/subscribe?u=91727179f1c05b357b43bb4d3&id=4122328387
github_ribbon_img: https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67

# Build settings
permalink: /blog/:title
paginate_path: /blog/page:num
paginate: 20
excerpt_separator: <!--break-->
markdown: redcarpet
highlighter: pygments
exclude: ["README.md", "vendor"]
gems:
- jekyll-redirect-from
